<?php

namespace ContainerAa623Tj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RFrW1sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rFr_W1s' shared service.
     *
     * @return \http\Client\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\IntervenatController::new()": the $request argument is type-hinted with the non-existent class or interface: "http\\Client\\Request".');
    }
}
