<?php

namespace ContainerAa623Tj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OBtiaCTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oBtiaCT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oBtiaCT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.rFr_W1s', NULL, 'Cannot determine controller argument for "App\\Controller\\IntervenatController::new()": the $request argument is type-hinted with the non-existent class or interface: "http\\Client\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
