<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAa623Tj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAa623Tj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAa623Tj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAa623Tj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAa623Tj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aa623Tj',
    'container.build_id' => '927f7bcc',
    'container.build_time' => 1671198595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAa623Tj');
