<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK9xoEQv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK9xoEQv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK9xoEQv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK9xoEQv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK9xoEQv\App_KernelDevDebugContainer([
    'container.build_hash' => 'K9xoEQv',
    'container.build_id' => 'd976dfd5',
    'container.build_time' => 1682086484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK9xoEQv');
