<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBnxflk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBnxflk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBnxflk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBnxflk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEBnxflk\App_KernelDevDebugContainer([
    'container.build_hash' => 'EBnxflk',
    'container.build_id' => '86cb1d70',
    'container.build_time' => 1668698463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBnxflk');
